server:
  port: 8090

spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        useCurrentUri: false
        registration:
          google:
            clientId:
            clientSecret:
            scope:
              - email
              - profile